// LLVM IR to TOSA IR Conversion
// Generated by Complete LLVM2TOSA Converter
// Supports all 68 LLVM instructions -> 66 TOSA operations

module {
func.func @axpy(%a: tensor<f32>, %x: tensor<?xf32>, %y: tensor<?xf32>) -> tensor<?xf32> {
    // AXPY operation: a*x + y
    // 1. Scalar a broadcasts and multiplies with vector x
    %mul_result = tosa.mul %x, %a : (tensor<?xf32>, tensor<f32>) -> tensor<?xf32>
    // 2. Add the result to vector y
    %add_result = tosa.add %mul_result, %y : (tensor<?xf32>, tensor<?xf32>) -> tensor<?xf32>
    return %add_result : tensor<?xf32>
  }

}
