# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mac/project/llvm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mac/project/llvm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mac/project/llvm/CMakeFiles /Users/mac/project/llvm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mac/project/llvm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named llvm2tosa

# Build rule for target.
llvm2tosa: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 llvm2tosa
.PHONY : llvm2tosa

# fast build rule for target.
llvm2tosa/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llvm2tosa.dir/build.make CMakeFiles/llvm2tosa.dir/build
.PHONY : llvm2tosa/fast

#=============================================================================
# Target rules for targets named converter_demo

# Build rule for target.
converter_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 converter_demo
.PHONY : converter_demo

# fast build rule for target.
converter_demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/converter_demo.dir/build.make CMakeFiles/converter_demo.dir/build
.PHONY : converter_demo/fast

#=============================================================================
# Target rules for targets named unit_tests

# Build rule for target.
unit_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit_tests
.PHONY : unit_tests

# fast build rule for target.
unit_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/build
.PHONY : unit_tests/fast

examples/simple_converter_demo.o: examples/simple_converter_demo.cpp.o
.PHONY : examples/simple_converter_demo.o

# target to build an object file
examples/simple_converter_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/converter_demo.dir/build.make CMakeFiles/converter_demo.dir/examples/simple_converter_demo.cpp.o
.PHONY : examples/simple_converter_demo.cpp.o

examples/simple_converter_demo.i: examples/simple_converter_demo.cpp.i
.PHONY : examples/simple_converter_demo.i

# target to preprocess a source file
examples/simple_converter_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/converter_demo.dir/build.make CMakeFiles/converter_demo.dir/examples/simple_converter_demo.cpp.i
.PHONY : examples/simple_converter_demo.cpp.i

examples/simple_converter_demo.s: examples/simple_converter_demo.cpp.s
.PHONY : examples/simple_converter_demo.s

# target to generate assembly for a file
examples/simple_converter_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/converter_demo.dir/build.make CMakeFiles/converter_demo.dir/examples/simple_converter_demo.cpp.s
.PHONY : examples/simple_converter_demo.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llvm2tosa.dir/build.make CMakeFiles/llvm2tosa.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llvm2tosa.dir/build.make CMakeFiles/llvm2tosa.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llvm2tosa.dir/build.make CMakeFiles/llvm2tosa.dir/main.cpp.s
.PHONY : main.cpp.s

src/CompleteConverter.o: src/CompleteConverter.cpp.o
.PHONY : src/CompleteConverter.o

# target to build an object file
src/CompleteConverter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llvm2tosa.dir/build.make CMakeFiles/llvm2tosa.dir/src/CompleteConverter.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/converter_demo.dir/build.make CMakeFiles/converter_demo.dir/src/CompleteConverter.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/CompleteConverter.cpp.o
.PHONY : src/CompleteConverter.cpp.o

src/CompleteConverter.i: src/CompleteConverter.cpp.i
.PHONY : src/CompleteConverter.i

# target to preprocess a source file
src/CompleteConverter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llvm2tosa.dir/build.make CMakeFiles/llvm2tosa.dir/src/CompleteConverter.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/converter_demo.dir/build.make CMakeFiles/converter_demo.dir/src/CompleteConverter.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/CompleteConverter.cpp.i
.PHONY : src/CompleteConverter.cpp.i

src/CompleteConverter.s: src/CompleteConverter.cpp.s
.PHONY : src/CompleteConverter.s

# target to generate assembly for a file
src/CompleteConverter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/llvm2tosa.dir/build.make CMakeFiles/llvm2tosa.dir/src/CompleteConverter.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/converter_demo.dir/build.make CMakeFiles/converter_demo.dir/src/CompleteConverter.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/CompleteConverter.cpp.s
.PHONY : src/CompleteConverter.cpp.s

tests/unit_test.o: tests/unit_test.cpp.o
.PHONY : tests/unit_test.o

# target to build an object file
tests/unit_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/unit_test.cpp.o
.PHONY : tests/unit_test.cpp.o

tests/unit_test.i: tests/unit_test.cpp.i
.PHONY : tests/unit_test.i

# target to preprocess a source file
tests/unit_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/unit_test.cpp.i
.PHONY : tests/unit_test.cpp.i

tests/unit_test.s: tests/unit_test.cpp.s
.PHONY : tests/unit_test.s

# target to generate assembly for a file
tests/unit_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/unit_test.cpp.s
.PHONY : tests/unit_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... converter_demo"
	@echo "... llvm2tosa"
	@echo "... unit_tests"
	@echo "... examples/simple_converter_demo.o"
	@echo "... examples/simple_converter_demo.i"
	@echo "... examples/simple_converter_demo.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/CompleteConverter.o"
	@echo "... src/CompleteConverter.i"
	@echo "... src/CompleteConverter.s"
	@echo "... tests/unit_test.o"
	@echo "... tests/unit_test.i"
	@echo "... tests/unit_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

